# Generated by Django 4.2.11 on 2024-06-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_cliente', models.CharField(max_length=50, verbose_name='Tipo Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(help_text='Ingrese Rut con guión, Ej: 123456789-0', max_length=10, unique=True)),
                ('nombre_cliente', models.CharField(max_length=50, unique=True, verbose_name='Nombre Cliente')),
                ('razon_social', models.CharField(max_length=50, unique=True, verbose_name='Razon Social')),
                ('direccion_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Cliente')),
                ('nombre_rep_cliente', models.CharField(max_length=50, verbose_name='Nombre Representante')),
                ('apellido_rep_cliente', models.CharField(max_length=50, verbose_name='Apellido Representante')),
                ('cargo_rep_cliente', models.CharField(max_length=50, verbose_name='Cargo')),
                ('email_rep_cliente', models.EmailField(max_length=50, unique=True, verbose_name='Email Cliente')),
                ('fono_rep_cliente', models.CharField(max_length=9, verbose_name='Fono Representante')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacion.tipo_cliente', verbose_name='Tipo Cliente')),
            ],
        ),
    ]
