# Generated by Django 4.2.11 on 2024-06-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania_Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compania_seguro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Commpania Seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empleado', models.CharField(help_text='Ingrese Rut con guión, Ej: 123456789-0', max_length=10, unique=True)),
                ('nombres_empleado', models.CharField(max_length=50, verbose_name='Nombres Empleado')),
                ('primer_apellido_empleado', models.CharField(max_length=50, verbose_name='Primer Apellido Empleado')),
                ('segundo_apellido_empleado', models.CharField(max_length=50, verbose_name='Segundo Apellido Empleado')),
                ('email_empresa', models.EmailField(max_length=50, unique=True, verbose_name='Email Empresa')),
                ('cargo_empleado', models.CharField(max_length=50, verbose_name='Cargo Empleado')),
                ('area_empleado', models.CharField(max_length=50, verbose_name='Area Empleado')),
                ('estado_contratacion', models.IntegerField(choices=[[0, 'Activo'], [1, 'No Activo'], [2, 'Otro']])),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_persona', models.CharField(help_text='Ingrese Rut con guión, Ej: 123456789-0', max_length=10, unique=True)),
                ('nombres_persona', models.CharField(max_length=50, verbose_name='Nombres Persona')),
                ('primer_apellido_persona', models.CharField(max_length=50, verbose_name='Primer Apellido Persona')),
                ('segundo_apellido_persona', models.CharField(max_length=50, verbose_name='Segundo Apellido Persona')),
                ('email_persona', models.EmailField(max_length=50, unique=True, verbose_name='Email Persona')),
                ('fono_persona', models.CharField(blank=True, max_length=9, null=True, verbose_name='Fono Persona')),
                ('fono2_persona', models.CharField(blank=True, max_length=9, null=True, verbose_name='Fono 2 Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prevision', models.CharField(max_length=50, verbose_name='Nombre Prevision')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_prestador', models.CharField(max_length=50, verbose_name='Tipo Prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador', models.CharField(max_length=50, verbose_name='Prestador')),
                ('tipo_prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacion.tipo_prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Fono_Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fono_compania', models.CharField(blank=True, max_length=9, null=True, verbose_name='Fono Persona')),
                ('compania_seguro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacion.compania_seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_compania', models.EmailField(max_length=50, unique=True, verbose_name='Email Persona')),
                ('compania_seguro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacion.compania_seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_persona', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Persona')),
                ('ficha_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacion.ficha_persona')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_contacto_cliente', models.CharField(max_length=50, verbose_name='Nombres Contacto Cliente')),
                ('primer_apellido_contacto_cliente', models.CharField(max_length=50, verbose_name='Primer Apellido Contacto Cliente')),
                ('segundo_apellido_contacto_cliente', models.CharField(max_length=50, verbose_name='Segundo Apellido Contacto Cliente')),
                ('cargo_contacto_cliente', models.CharField(max_length=50, verbose_name='Cargo Contacto Cliente')),
                ('email_contacto_cliente', models.EmailField(max_length=50, unique=True, verbose_name='Email Contacto Cliente')),
                ('fono_contacto_cliente', models.CharField(max_length=9, verbose_name='Fono Contacto Cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacion.cliente')),
            ],
        ),
    ]
